[tool.briefcase]
project_name = "Machine Learning Portal"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/ml-app"
license = "BSD license"
author = 'Tim Duffy, Jacob Frost'
author_email = "duffyjtim@gmail.com"

[tool.briefcase.app.ml-app]
formal_name = "Machine Learning Portal"
description = "Simple GUI that launches jupyter notebooks about ML"
icon = "src/ml_app/resources/ml-app"
sources = ['src/ml_app']
requires = []


[tool.briefcase.app.ml-app.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.ml-app.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.ml-app.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.ml-app.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.ml-app.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
